name: Deploy to Hostoo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FTP credentials
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_PORT: ${{ secrets.FTP_PORT }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "FTP_SERVER=${{ secrets.FTP_SERVER }}" >> $GITHUB_ENV
        echo "FTP_PORT=${{ secrets.FTP_PORT }}" >> $GITHUB_ENV
        echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
        echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV

    - name: Deploy to Hostoo via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ env.FTP_SERVER }}
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
        port: ${{ env.FTP_PORT }}
        local-dir: ./public
        server-dir: /


